// Writes the table of English verse counts the importer checks against.
//
//   dart run tool/build_versification.dart
//
// Taken from the Berean Standard Bible, because that is the translation the
// cross-reference data was anchored to: the question the table answers is
// not "is this a normal Bible" but "does this Bible number its verses the
// way our cross-references assume".
//
// Output: lib/src/model/versification_table.dart
import 'dart:io';

import 'package:openword/src/model/bib_file.dart';
import 'package:openword/src/model/book_meta.dart';

const String source = 'assets/bible/eng-bsb.bib';
const String output = 'lib/src/model/versification_table.dart';

void main() {
  final bible = BibFile.decode(File(source).readAsBytesSync());

  final rows = <String>[];
  var chapters = 0;
  for (final book in bible.books) {
    if (book.section == BookSection.deuterocanon) continue;
    final counts = [for (final c in book.outline) c.verseCount];
    chapters += counts.length;
    rows.add("  '${book.code}': '${counts.join(' ')}',");
  }

  File(output).writeAsStringSync('''
// GENERATED by tool/build_versification.dart from $source.
// Do not edit by hand.

/// How many verses each chapter of the English Protestant Bible has.
///
/// The counts are the Berean Standard Bible's, which is the translation the
/// bundled cross-references were anchored to. The deuterocanonical books
/// are left out on purpose: their numbering differs between English
/// editions as much as between schemes — the three translations bundled
/// here disagree over Greek Esther, Sirach, Baruch and 4 Maccabees — so
/// comparing them would raise a false alarm on an ordinary import.
///
/// ${bible.books.where((b) => b.section != BookSection.deuterocanon).length} books, $chapters chapters.
const Map<String, String> englishVerseCounts = {
${rows.join('\n')}
};
''');

  stdout.writeln('$output: ${rows.length} books, $chapters chapters');
}
